instantview/instantview/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from instantview.views import IndexView, signup


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url('accounts/login/$', auth_views.LoginView.as_view(), name='login'),
    url('accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', signup, name='signup'),
    url(r'^photos/', include('photo.urls', namespace='photo')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instantview/photo/urls.py
from django.conf.urls import url

from . import views
from .models import Photo


urlpatterns = [
    url(r'^$', views.PhotoListView.as_view(), name='list'),
    url(r'^upload/$', views.PhotoUploadView.as_view(), name='upload'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.PhotoDeleteView.as_view(), name='delete'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.PhotoUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/$', views.PhotoDetailView.as_view(), name='detail'),
]

instantview/photo/models.py
from base64 import b64encode
import json
import requests
from django.conf import settings
from django.db import models


class Photo(models.Model):
    photo = models.FileField(upload_to='photos/%Y/%m/%d/')
    description = models.CharField(max_length=255, blank=True, null=False, default='desciption')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=False, on_delete=models.CASCADE, editable=False)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-updated_at',)

    def save(self, *args, **kwargs):
        created = self.id is None
        super(Photo, self).save(*args, **kwargs)
        if created:
            object_data = self.get_google_visionapi_data()
            try:
                PhotoGoogleVisionDetails.objects.filter(photo=self).delete()
                for i in object_data['responses'][0]['labelAnnotations']:
                    PhotoGoogleVisionDetails.objects.create(
                        photo=self,
                        description=i['description'],
                        score=i['score']
                    )
            except (IndexError, KeyError, TypeError):
                pass

    def get_google_visionapi_data(self, detection_types=None, max_result=5):

        default_detection_types = ['LABEL_DETECTION']

        dt = default_detection_types if detection_types is None else detection_types
        features = [{'type': i, 'maxResults': max_result} for i in dt]
        self.photo.open()
        image = {'content': b64encode(self.photo.read()).decode('ascii')}
        request = {'requests': [{'image': image, 'features': features}]}
        response = requests.post(settings.GOOGLE_VISION_API_URL, json=request)
        if response.status_code != 200:
            return
        return response.json()


class PhotoGoogleVisionDetails(models.Model):
    photo = models.ForeignKey(Photo, editable=False, null=False, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, null=False, editable=False)
    score = models.DecimalField(max_digits=9, decimal_places=8, editable=False)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-score',)

instantview/instantview/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name='index.html'


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

instantview/photo/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, DetailView, ListView,\
    TemplateView, UpdateView

from photo.models import Photo

class UserObjectsMixin:

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)


class PhotoListView(LoginRequiredMixin, UserObjectsMixin, ListView):
    paginate_by = 16 # 4x4 grid


class PhotoDetailView(LoginRequiredMixin, UserObjectsMixin, DetailView): pass


class PhotoUploadView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = 'description', 'photo'

    def get_success_url(self):
        return reverse('photo:detail', kwargs={'pk': self.object.id})

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PhotoUploadView, self).form_valid(form)


class PhotoUpdateView(LoginRequiredMixin, UserObjectsMixin, UpdateView):
    model = Photo
    fields = 'description', 'photo'

    def get_success_url(self):
        return reverse('photo:detail', kwargs={'pk': self.object.id})


class PhotoDeleteView(LoginRequiredMixin, UserObjectsMixin, DeleteView):

    def get_success_url(self):
        return reverse('photo:list')

instantview/instantview/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}Instant View{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<body>
	{% block navbar %}
	<nav class="navbar navbar-inverse" style="margin-bottom: 0px">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'index' %}">Instant View</a>
			</div>
			<ul class="nav navbar-nav">
				<li class="active"><a href="{% url 'index' %}">Home</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
				<p class="navbar-text">Logged as {{ user.username }}</p>
				<li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
				{% else %}
				<p class="navbar-text">not logged in</p>
				<li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
				<li><a href="{% url 'signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
				{% endif %}
			</ul>
		</div>
	</nav>
	{% endblock %}

	<div class="panel panel-default">
		<div class="panel-heading">
			{% block header %}<h1>Instant View</h1>{% endblock %}
		</div>

		<div class="panel-body">
			{% block content %}{% endblock %}
		</div>

		<div class="panel-footer">Instant View</div>
			{% block footer %}{% endblock %}
		</div>
	</div>

</body>
</html>

instantview/instantview/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Welcome in Instant View {% if user.is_authenticated %}{{ user.username }}{% endif %}</h1>
{% if user.is_authenticated %}
	<a href="{% url 'photo:list' %}" class="btn btn-info" role="button">photo gallery</a>
{% else %}
<p>Please <a href="{% url 'login' %}">log in</a> or <a href="signup">sign up</a></p>
{% endif %}
{% endblock content %}

instantview/instantview/templates/pagination.html
<div class="container">
	<ul class="pagination">
		<li {% if not page_obj.has_previous %}class="disabled"{% endif %}><a {% if page_obj.has_previous %}href="?page=1"{% endif %}>&lt&lt</a></li>
		<li {% if not page_obj.has_previous %}class="disabled"{% endif %}><a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %}>&lt</a></li>
		<li class="active"><a>{{ page_obj.number }}</a></li>
		<li {% if not page_obj.has_next %}class="disabled"{% endif %}><a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}>&gt</a></li>
		<li {% if not page_obj.has_next %}class="disabled"{% endif %}><a {% if page_obj.has_next %}href="?page={{ paginator.num_pages }}"{% endif %}>&gt&gt</a></li>
	</ul>
</div>

instantview/instantview/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
		{{ form.errors }}
    {{ form.as_p }}
    <button type="submit" class="btn btn-default">Sign up</button>
  </form>
{% endblock %}

instantview/photo/templates/photo/photo_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete the <strong>{{ object.description }}</strong> photo?</h1>
<form action="" method="post">
	  {% csrf_token %}
<input type="submit" value="Delete" class="btn btn-danger">
<a href="{% url 'photo:list' %}" class="btn btn-default">to list</a>
<a href="{% url 'photo:detail' object.id %}" class="btn btn-default">to details</a>
</form>
{% endblock content %}

instantview/photo/templates/photo/photo_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h2>Image details</h2>
	<h4>Description: <strong>{{ object.description }}</strong></h4>
	<table class="table table-striped table-bordered table-condensed" style="width:50%">
		<tr>
			<th colspan=2 style="text-align: center">Google Vision tags for this photo</th>
		</tr>
  	<tr>
   		<th>Label</th>
    	<th>Score</th>
  	</tr>
		{% for i in object.photogooglevisiondetails_set.all %}
		<tr>
			<td>{{ i.description }}</td>
			<td>{{ i.score }}</td>
		</tr>
		{% endfor %}
</table>
	<img class="img-responsive" src="{{ object.photo.url }}" alt="photo" width="100%" height="auto" style="padding-bottom: 20px"> 
	<a href="{% url "photo:delete" object.id %}" class="btn btn-danger">delete</a>
	<a href="{% url "photo:update" object.id %}" class="btn btn-primary">update</a>
	<a href="{% url "photo:list" %}" class="btn btn-default">to list</a>
</div>
{% endblock %}

instantview/photo/templates/photo/photo_form.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
	<h2>{% if object %}Update{% else %}Upload{% endif %} a photo</h2>
  <form action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.non_field_errors }}
		{% for field in form %}
    <div class="form-group">
			{{ field.errors }}
			<label for="{{ field.id_for_label }}">{{ field.label }}</label>
			{{ field }}
    </div>
		{% endfor %}
		<button type="submit" class="btn btn-primary">{% if object %}update{% else %}upload{% endif %}</button>
		<a href="{% url "photo:list" %}" class="btn btn-default">to list</a>
		{% if object %}
		<a href="{% url "photo:detail" object.id %}" class="btn btn-default">to details</a>
		{% endif %}
  </form>
</div>
{% endblock content %}

instantview/photo/templates/photo/photo_list.html
{% extends 'base.html' %}

{% comment %}
{% block content %}
<h1>Photos List</h1>
{% if object_list %}
    <ul>
    {% for photo in object_list %}
		<li>
			  <a href="{% url 'photo:detail' photo.id %}">{{ photo.description }}</a>
				<a href="{% url 'photo:delete' photo.id %}">Delete photo</a>
		</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No photos are available.</p>
{% endif %}

{% block content %}
<h1>Photos List</h1>
<p><a href="{% url 'photo:upload' %}">Upload a photo</a></p>
{% for photo in object_list %}
<div class="gallery">
	<a href="{% url "photo:detail" photo.id %}">
		<img src="{{ photo.photo.url }}" alt="photo" width="300", height="200">
  </a>
	<div class="desc">{{ photo.description }}</div>
</div>
{% endfor %}
{% endblock %}
{% endcomment %}

{% block content %}
<div class="container">
  <h2>Image Gallery</h2>
  <p>Click on the images to get the details.</p>
  <div class="row">
		{% for photo in object_list %}
    <div class="col-md-3">
      <div class="thumbnail">
				<a href="{% url "photo:detail" photo.id %}">
					<img src="{{ photo.photo.url }}" alt="photo">
        </a>
        <div class="caption">
					<p>{{ photo.description }}</p>
					<a href="{% url "photo:update" photo.id %}" class="btn btn-primary">update</a>
					<a href="{% url "photo:delete" photo.id %}" class="btn btn-danger">delete</a>
        </div>
      </div>
    </div>
		{% endfor %}
  </div>
	{% include "pagination.html" %}
	<a href="{% url "photo:upload" %}" class="btn btn-primary">upload a photo</a>
</div>
{% endblock %}